[package]
name = "rscomp"
version = "0.0.0"
edition = "2021"
# autotests = false
publish = false

[workspace]

[[bin]]
name = "rscomp"
path = "main.rs"

[dependencies]
astnode = { path = "astnode" }
libcomp = { path = "libcomp" }
# regex = "1.5"
