[package]
name = "astnode"
version = "0.0.0"
edition = "2021"
autotests = false
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version ="1.0.82", features=["full", "extra-traits"] }
quote = "1.0.16"
convert_case = "0.5.0"
proc-macro2 = "1.0.36"
# TODO
